#!/usr/bin/env python

import sys

from rqt_gui.main import Main


def add_arguments(parser):
    group = parser.add_argument_group('Options for rqt_send_file plugin')
    group.add_argument('topic', nargs='?', help='The topic name to publish the file content')

main = Main()
sys.exit(main.main(
    sys.argv,
    standalone='rqt_send_file/SendFile',
    plugin_argument_provider=add_arguments))
